version: "3"
services:
  postgres_cadastro:
    container_name: quarkus_postgres_cadastro
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"